Add missing greenlet library
Without greenlet, scrapy failed with following error:

ValueError: the greenlet library is required to use this function. No module named 'greenlet'